project: ruatd
classification: binary

data:
  train: /root/RuATD/data/binary/train.csv
  val: /root/RuATD/data/binary/val.csv
  test: /root/RuATD/data/binary/test.csv

max_len: 512

batch_size: 40
num_workers: 4
pin_memory: True
device: cuda
device_ids: [0, 1, 2, 3, 4]
epochs: 5
lr: 0.00001
num_classes: 2
model: IlyaGusev/mbart_ru_sum_gazeta #DeepPavlov/rubert-base-cased #DeepPavlov/xlm-roberta-large-en-ru 

checkpoint: /root/RuATD/checkpoints/
submission: /root/RuATD/submissions/
