project: ruatd
classification: binary

data:
  train: /root/RuATD/data/binary/train.csv
  val: /root/RuATD/data/binary/val.csv
  test: /root/RuATD/data/binary/test.csv

max_len: 256

batch_size: 40
num_workers: 4
pin_memory: True
device: cuda
device_ids: [0, 1, 2, 3, 4]
epochs: 3
lr: 0.00001
num_classes: 2
num_folds: 5
model: DeepPavlov/xlm-roberta-large-en-ru-mnli 
#DeepPavlov/distilrubert-tiny-cased-conversational
#sberbank-ai/sbert_large_nlu_ru #IlyaGusev/mbart_ru_sum_gazeta #DeepPavlov/rubert-base-cased #MoritzLaurer/mDeBERTa-v3-base-mnli-xnli #DeepPavlov/xlm-roberta-large-en-ru-mnli 
###Geotrend/distilbert-base-ru-cased
##
## #clips/mfaq  
##sberbank-ai/rugpt3xl

checkpoint: /root/RuATD/checkpoints/
submission: /root/RuATD/submissions/
