project: ruatd
classification: multiclass

data:
  train: /root/RuATD/data/multiclass/train.csv
  val: /root/RuATD/data/multiclass/val.csv
  test: /root/RuATD/data/multiclass/test.csv

max_len: 512

batch_size: 40
num_workers: 4
pin_memory: True
device: cuda
device_ids: [0, 1, 2, 3, 4]
epochs: 3
lr: 0.00001
num_classes: 14
model: IlyaGusev/mbart_ru_sum_gazeta #DeepPavlov/rubert-base-cased #DeepPavlov/xlm-roberta-large-en-ru  

checkpoint: /root/RuATD/checkpoints/
submission: /root/RuATD/submissions/
